# Generated by Django 5.2.6 on 2025-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
