# Generated by Django 5.2.6 on 2025-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_mainuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
