# Generated by Django 5.2.6 on 2025-09-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_mainuser_groups_mainuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
