# Generated by Django 5.2.6 on 2026-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_mainuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
