# Generated by Django 5.2.6 on 2025-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_assignment_submitted_count_assignment_total_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Submitted', 'submitted'), ('Re-submitted', 're-submitted'), ('Completed', 'completed')], default='Pending', max_length=20),
        ),
    ]
