# Generated by Django 5.2.6 on 2025-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_alter_submission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='upload_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resume',
            name='keyword_match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resume',
            name='optimized_resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume/optimized/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_file',
            field=models.FileField(default=1, upload_to='resumes/originals/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
