# Generated by Django 5.2.6 on 2025-11-02 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0006_rename_upload_at_resume_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='plan',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='name',
            field=models.CharField(default='Personalized Study Plan', max_length=255),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=400)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('difficulty_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Education.studyplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True, null=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studyplan',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='Education.studyplanrequest'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SyllabusUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='syllabus/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.BooleanField(default=False)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studyplanrequest',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Education.syllabusupload'),
        ),
        migrations.CreateModel(
            name='TopicDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=400)),
                ('difficulty', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_difficulties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
