# Generated by Django 5.2.6 on 2025-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_rename_generated_at_studyplan_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabusupload',
            old_name='uploaded_file',
            new_name='syllabus_file',
        ),
        migrations.AddField(
            model_name='syllabusupload',
            name='performance_file',
            field=models.FileField(default=1, upload_to='performance/'),
            preserve_default=False,
        ),
    ]
